mongodb-js/mongodb-core

lib/cursor.js
test/tests/functional/cursor_tests.js

Fix cursor hanging when next() called on exhausted cursor

---

index.js

Add ScramSHA1to index.js for easy access.

add ScramSHA1 to index.js

---

lib/wireprotocol/2_4_support.js

Hi Christian,
Re: Automattic/mongoose#3371, I can confirm that 2.4 support is swallowing callback exceptions thanks to [this line](https://github.com/christkv/mongodb-core/blob/5b49740860642c3750ac5c7f802edc9fc219b881/lib/topologies/server.js#L244).  This patch makes sure to wrap callbacks in `nextTick()`. To see the error swallowing in action, run the below script against a 2.4.x standalone mongod.
```javascript
var core = require('mongodb-core');
var server = new core.Server({ host: 'localhost', port: 27017 });
server.on('connect', function() {
server.insert('test.writes', { x: 1 }, function(err) {
throw new Error('fail!');
});
});
server.connect();
```
I'd add a test for this but that would require working with `process.on('uncaughtException');`, which is usually not a good idea in …

don't swallow callback errors for 2.4 single server

---

lib/topologies/server.js

Fixing copy/paste error. I'm not sure though if the new description is the best for this function.

Fix Server.prototype.cursor description

---

lib/cursor.js

Prevent Maximum call stack exceeded by calling all callbacks on nextTick

use process.nextTick for handleCallback

---

lib/connection/connection.js

In the case of an invalid private key, the core node tls module raises
the exception instead of emitting an error event like all other errors.
This addresses this case and other potential anomalies.

Handle rogue SSL exceptions.

---

lib/connection/connection.js

Connection.socketTimeoutMS property setter error message adjusted: boolean to number

socketTimeoutMS property setter err message adjusted

---

lib/topologies/server.js

Otherwise the pool fills up with newConnections which are never moved into availableConnections.
Still there are a couple of questions:
- only connections created in the _createConnection() method go through the process of emitting the connection event for authentication, but not the connection created in the connect() method (it simply goes straight into availableConnections.) Shouldn't all new connection emit the connection event?
- should _createConnection() check for listener to the connection event and if none found move the new connection directly into availableConnections?
- should the connection handler be installed after providers have been reauthenticated?
Steps to reproduce:
1- create a pool
2- wait for the pool to timeout and for the server to reconnect. At that point the …

re-install connectionHandler after server reconnection

---

lib/connection/pool.js

properly reset socketTimeout

---

test/tests/functional/single_mocks/compression_tests.js
test/tests/functional/single_mocks/timeout_tests.js

test(single_mocks): single mocks refactor to mocha style

---

package.json
test/tests/functional/rs_mocks/add_remove_tests.js
test/tests/functional/rs_mocks/all_servers_close_tests.js
test/tests/functional/rs_mocks/connection_tests.js
test/tests/functional/rs_mocks/failover_tests.js
test/tests/functional/rs_mocks/maintanance_mode_tests.js
test/tests/functional/rs_mocks/monitoring_tests.js
test/tests/functional/rs_mocks/no_primary_found_tests.js
test/tests/functional/rs_mocks/operation_tests.js
test/tests/functional/rs_mocks/primary_loses_network_tests.js
test/tests/functional/rs_mocks/read_preferences_tests.js

test(rs_mocks): rs mocks refactor to mocha style

---

test/tests/functional/mongos_mocks/mixed_seed_list_tests.js
test/tests/functional/mongos_mocks/multiple_proxies_tests.js
test/tests/functional/mongos_mocks/proxy_failover_tests.js
test/tests/functional/mongos_mocks/proxy_read_preference_tests.js
test/tests/functional/mongos_mocks/single_proxy_connection_tests.js

test(mongos_mocks): mongos mocks refactor to mocha style

---

package.json
test/tests/functional/basic_replset_server_auth_tests.js
test/tests/functional/basic_single_server_auth_tests.js
test/tests/functional/client_metadata_tests.js
test/tests/functional/cursor_tests.js
test/tests/functional/error_tests.js
test/tests/functional/extend_cursor_tests.js
test/tests/functional/max_staleness_tests.js
test/tests/functional/mongos_server_selection_tests.js
test/tests/functional/operation_example_tests.js
test/tests/functional/operations_tests.js
test/tests/functional/pool_tests.js
test/tests/functional/server_tests.js
test/tests/functional/tailable_cursor_tests.js

@mbroadst here are the rest of the tests

[NODE-1096] Converting tests to run with mongodb-test-runner, round 2

---

lib/topologies/replset.js
lib/topologies/replset_state.js

fix: fix typo

---

lib/connection/connection.js
test/tests/functional/pool_tests.js

Fixing leaky connection in 2.0 branch.

fix(connection): fixing leaky connection

---

lib/connection/connection.js

Hi, this is related with #242.

fix(connection): added missed tls option ecdhCurve

---

lib/connection/connection.js

feat(ssl): adding ssl options ciphers and ecdhCurve

---

lib/cursor.js

Re: https://github.com/Automattic/mongoose/issues/5794#issuecomment-356068335, https://github.com/mongodb-js/mongodb-core/pull/233#issuecomment-356069085

fix: port fix for #233 to 3.0.0 branch

---

lib/topologies/replset.js

Backport of NODE-1269 to 2.0
Is it worth adding a test for this?

fix(replset): remove primary from topology on failure to connect

---

lib/cursor.js
lib/sessions.js

Adds ability to tell difference between implicit and explicit
sessions, and adds part of implicit session support to
cursors.
Part of NODE-1326

feat(sessions): adding implicit cursor session support

---

lib/uri_parser.js
test/tests/unit/mongodb_srv_spec_tests.js

fix(uri_parser): support a default database on mongodb+srv uris

---

lib/topologies/replset.js
test/tests/unit/replset/step_down_tests.js

fix(replset): only remove primary if primary is there

---

lib/connection/apm.js
lib/connection/commands.js
lib/connection/pool.js
lib/cursor.js
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js
lib/topologies/shared.js
lib/wireprotocol/2_6_support.js
lib/wireprotocol/3_2_support.js
test/tests/functional/cursor_tests.js
test/tests/functional/operations_tests.js
test/tests/functional/server_tests.js

This is the buddy implementation to https://github.com/mongodb/node-mongodb-native/pull/1675, see that PR for more details.

NODE-1390 improve command monitoring implementation (CORE)

---

index.js
lib/auth/defaultAuthProviders.js
lib/auth/scram.js
lib/connection/pool.js
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js
package.json
test/tests/functional/basic_single_server_auth_tests.js
test/tests/unit/scram_iterations_tests.js

No longer WIP.
Includes SCRAM-SHA-256, saslprep for Node >= 6, and Mechanism Negotiation.
Fixes NODE-1303
Fixes NODE-1311

Adds saslprep and SCRAM-SHA-256

---

lib/cursor.js
lib/error.js
lib/sessions.js
lib/topologies/replset.js
lib/topologies/server.js
lib/transactions.js
lib/wireprotocol/3_2_support.js
lib/wireprotocol/shared.js

This is the core component to the changes required to pass the current revision of the transactions specification YAML tests.

NODE-1374 Implement final revision of transactions (core)

---

lib/cursor.js

feat(cursor): store operation time from initial query

---

.evergreen/config.yml
.evergreen/run-atlas-tests.sh
package.json
test/atlas.js

test(atlas): atlas connectivity tests

---

lib/connection/pool.js
lib/error.js

fix(error): attach command response to MongoWriteConcernError

---

package.json

fix(kerberos): loosen restrictions on kerberos versions

---

lib/sessions.js

Fixes [NODE-1518](https://jira.mongodb.org/browse/NODE-1518)

fix(sessions): add `toBSON` method to `ClientSession`

---

lib/connection/commands.js
lib/cursor.js
test/tests/unit/response_test.js

Fixes [NODE-1528](https://jira.mongodb.org/browse/NODE-1528)

fix(commands): check doc.cursor errors

---

lib/uri_parser.js
test/tests/unit/connection_string_spec_tests.js

fix(uri_parser): ensure default port is 27017

---

lib/cursor.js
lib/topologies/server.js
lib/utils.js

Created a utility function collationNotSupported() that will check
if collation is supported by the server, and if not, call the callback 
with an error.
Fixes NODE-1522

refactor(collation): utility function for checking collation support

---

lib/connection/commands.js
lib/wireprotocol/2_6_support.js
lib/wireprotocol/3_2_support.js

revert refactor(bson): default `checkKeys` to false

---

lib/auth/scram.js
lib/connection/commands.js
lib/connection/connection.js
lib/connection/pool.js
lib/topologies/replset_state.js
lib/topologies/shared.js
test/tests/functional/server_tests.js
test/tests/unit/common.js
test/tests/unit/scram_iterations_tests.js

Replace Buffer constructor with buffer.alloc and buffer.from
Fixes Node-1461

fix(buffer): replace deprecated Buffer constructor

---

lib/error.js

A quick refactor I was making during SDAM work, seemed unit enough to make it in as an independent commit.

refactor(error): modernize and clean up error classes

---

index.js
lib/utils.js
package.json

Optionally require and export EJSON from core for use in native's APM logging feature.

fix(EJSON): export the result of optionally requiring EJSON

---

lib/connection/connection.js
test/tests/functional/operations_tests.js
test/tests/functional/pool_tests.js
test/tests/functional/rs_mocks/add_remove_tests.js
test/tests/unit/mongos/reconnect_tests.js

Implements fast fallback and refactors connection
to allow family to be specified for ssl and unsecure
connections.
Fixes NODE-1580

feat(connection): Implement fast fallback

---

lib/uri_parser.js
test/tests/unit/connection_string_spec_tests.js

fix(uri_parser): use admin as default auth.db

---

lib/auth/gssapi.js

fix(gssapi): check lowercase and camelCase gssapiServiceName option

---

lib/connection/connection.js
test/tests/functional/pool_tests.js
test/tests/functional/rs_mocks/add_remove_tests.js

This reverts commits:
956d5a2765edee0d1a8fabafe9cb43d26ff04ce5.
60646a70cff899c68378776e785afc56f76deeb9.
41e3d5e8ef8865963521160292449e4c1a328110.
68a6656041bb2c5e6ae361268587942184ebbfb4.
721ca6f479ffab5d39f082be65633762197b1d47.
6d821515ad4aed360b212b9d5abb329c11c8fcde.
719781531cec43ab01e8208c3fd0aacb8e0ff234.
6dff3266a701470499fa7a63e689f6de9c9a5355.
b0fb2e32e6e2b3c3ff2cb6a024108c3e3c2051e6.
t622394a571855c146a165416c53e7e3f3bd2c657.

Revert "feat(connection): Implement fast fallback"

---

.evergreen/config.yml

chore(evg): drop zSeries for all but rhel, reintroduce rhel72

---

lib/connection/connection.js

Hey !
I just came across this typo.
Peace !

docs(connection): fix typo

---

lib/uri_parser.js
test/tests/unit/connection_string_tests.js

**NOTE:** this builds on the work of the previous PR, and as such looks like a much larger changeset than it is.
Fixes NODE-1675

fix(uri-parser): add exemption list for number coercion in options

---

lib/sdam/server.js
lib/sdam/server_description.js
lib/sdam/topology.js

This enables authentication for the new SDAM layer with a relatively minor changeset!
NODE-1620

refactor(server): introduce authentication to server class

---

lib/auth/gssapi.js
lib/auth/sspi.js
lib/utils.js

refactor(kerberos): throw runtime error for missing kerberos module

---

.travis.yml

chore: updating MongoDB versions in travis

---

lib/topologies/mongos.js
test/tests/functional/extend_cursor_tests.js

NODE-1761
supersedes #365 
fixes #292 #374

fix(mongos): ensure servers are properly cleaned up when destroyed

---

lib/uri_parser.js

Change options and auth handling to leverage parsed URI object
When using a `mongodb+srv://` record and a password containing certain special characters, the URI would be perceived as malformed, even if the password was URI-encoded. This PR fixes the password handling to be more in line with non-SRV parsing.

fix(uri_parser): uri-encoded auth handling

---

lib/sdam/server.js

fix(topology): clear timeouts for monitor on topology close

---

lib/cursor.js

At first glance this just looks like its merging two functions into
a single, unweildy mega-function... which is sort of what it does.
But! This does a few things for us:
- reduces an implicit required recursive call for every cursor
by combining the initialization code with a call to the first
find command
- places the preparation of the find command (from WireProtocol)
with the actual execution (`pool.write`), which allows us to
better imagine moving those steps into the wireprotocol in
lock-step. This is good because it takes us one step closer
to actually having a consistent wire protocol api, and ceasing
rogue command construction in the codebase
NODE-1785

refactor(cursor): merge and simplify `nextFunction`

---

lib/cursor.js
lib/wireprotocol/2_6_support.js
lib/wireprotocol/3_2_support.js

refactor(wire-protocol): introduce wire protocol `query` method

---

lib/sessions.js

fix(transactions): write concern is always majority on txn retry

---

lib/uri_parser.js

fix(uri_parser): fix normalizing option names in connection string

---

lib/auth/scram.js

fix(scram): allow errors to be passed through callbacks

---

lib/sessions.js

Fixes NODE-1877
Test changes to native on the way

feat(withTransaction): retry transaction commit on wtimeout

---

lib/connection/connect.js

Fixes NODE-1841.
I currently have no way to test this in Core, hence this being WIP.

chore: disable tls renegotiation where possible

---

lib/connection/connect.js
test/tests/unit/connect_tests.js

fix: do not attempt to auth against an arbiter

---

lib/uri_parser.js
test/tests/unit/connection_string_tests.js

fix(uri_parser): support URI Options spec tests

---

lib/sdam/srv_polling.js
lib/sdam/topology.js
lib/sdam/topology_description.js
lib/uri_parser.js
package-lock.json
package.json
test/tests/functional/srv_polling_tests.js

Fixes NODE-1745
TODO list:
* See here: https://github.com/mongodb/node-mongodb-native/pull/1963
* Logging added with https://github.com/mongodb-js/mongodb-core/pull/423/commits/7f78c017fc622ca55117480ac989fe50117e8f9f

feat(srvPolling): Add support for srv polling to native topology

---

lib/topologies/read_preference.js

Native PR: https://github.com/mongodb/node-mongodb-native/pull/1985

feat(readPreference): add ReadPreference.fromOptions

---

lib/connection/command_result.js

fix(command_result): return entire result in toJSON

---

lib/sessions.js

fix(transactions): send recovery token on abortTransaction

---

lib/connection/connect.js
test/tests/unit/connect_tests.js

fix(connect): ensure connection errors are MongoNetworkErrors

---

docs/reference/README.md
docs/reference/static/js/java.js
docs/reference/themes/mongodb/README.md
docs/reference/themes/mongodb/theme.toml

docs(links): do not link to java
