lib/cursor.js
`findOne()` has some absurd behavior right now: it'll error out if the document returned has an 'errmsg' field, it'll only return only `{x:1}` of `{results:[{x:1}]}`. This is because core is treating it as a command cursor. I'm pretty sure you'll also get this behavior if you use `find()` and it happens to only return one doc. I'm not 100% sure this change is correct, but it passes tests (both core and driver) and fixes the issue.
Also, I don't see any cases where the code in L193-196 actually executes, except for the degenerate case where the user happened to insert a document with a `result` key, so I just got rid of it.
=> NODE-351: Don't treat findOne() as a command cursor

lib/cursor.js
```javascript
var options = {
tailable: true,
awaitData: true
};
var cursor = push.find({processed: false}, options);
```
When there is no document matching the given filter, cursor is closed immediately and doesn't listen for new documents. By this little change I was able to achieve a correct behavior - cursor is waiting for new documents.
Although I spent a lot of time exploring how driver works, I'm not 100% sure this is a correct fix. It passes all the tests and our applications are working properly.
=> Prevent closing tailable cursor when initial query returns zero documents

lib/error.js
https://jira.mongodb.org/browse/NODE-417
From that issue, this makes it so that the errors generated with `MongoError` now behave in a more logical manner when they are thrown in normal flow or asserted in tests. Previously due to the stack mechanics the message would often be lost making debugging much more challenging.
=> ISSUE: NODE-417 Resolution. Improving behavior of thrown errors

lib/error.js
A not-authorized error from a cursor returns a result that looks like this: `[ { '$err': 'not authorized for query on gh2942.users', code: 13 } ]`
That gives us the confusing `MongoError: n/a` error message:
```
MongoError: n/a
at Function.MongoError.create (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
at queryCallback (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:34)
at Callbacks.emit (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)
at null.messageHandler (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:219:23)
at Socket.<anonymous> …
```
=> Bubble up auth errors properly

lib/topologies/server.js
Each time the driver attempts to reconnect, the driver ticks down the number of available reconnect tries. When it successfully reconnects that number is left permanently declined. This pull request makes it so that when a successful reconnect occurs, the number is increased back to it's allowed limit.
=> After reconnect, it updates the allowable reconnect retries to the option settings

lib/connection/connection.js
=> Reset connectionTimeout after it's overwritten by tls.connect.

lib/topologies/replset.js
If you pass `connectWithNoPrimary` then `secondaryOnlyConnectionAllowed` is set to true but then this breaks a primary-only connection state. If `secondaryOnlyConnectionAllowed` is true then `isConnected` just returned if there was a secondary connected instead of allowing just a primary to still be connected.
=> Still allow primary only connection if secondaryOnly is true

lib/connection/connection.js
=> apply toString('hex') to each buffer in an array when logging

lib/connection/pool.js, lib/topologies/server.js
After migrating to mongo driver 2.x we got this error (including here for full context):
```
TypeError: Cannot read property 'isConnected' of undefined
at executeSingleOperation (/usr/local/lib/node_modules/auth0-api2/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:702:17)
at Server.command (/usr/local/lib/node_modules/auth0-api2/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:830:12)
at /usr/local/lib/node_modules/auth0-api2/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:364:12
at /usr/local/lib/node_modules/auth0-api2/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:353:18
at ScramSHA1.reauthenticate (/usr/local/lib/node_modules/auth0-api2/node_modules/mongodb/node_modules/mongodb-core/lib/aut …
```
=> Resetting index when capping connection pool

lib/topologies/replset.js, lib/topologies/replset_state.js
Currently if you open a connection to a replica set including an arbiter, and you attempt to close it, the process will stay open forever. This is due to two issues, the first is that we don't close arbiter connections, the second is the that the haTimer has to wait to expire. This pull request closes arbiters and unifies the setting of the various haTimers so that on a ReplSet.destroy() we can clear the timer and the process will close immediately. Once merged, when a db.close() is performed everything cascades properly and the process will be able to exit.
I'm testing this on mongodb 2.6 + node 0.12.7, but judging from the code I believe it should occur with all versions of Mongo / Node.
Test case:
```js
var mongodb = require("mongodb");
var async = require("async");
// change to your …
```
=> Allow node process to close after db.close() when using ReplSet

lib/topologies/server.js
Hi Christian,
Re: Automattic/mongoose#3481. This issue is hard to repro consistently and really only happens if you get very unlucky, which is why I didn't include a test (figured you might have some ideas on that front). The general idea is that if you're connected to a standalone mongod and happen to have a write going when the mongod dies, the server will swallow the connection pool error, try to reconnect, and leave a callback hanging. Here's the debug output:
```
[DEBUG-Server:26752] 1447957927937 executing command [{"ns":"test.$cmd","cmd":{"insert":"numbers","documents":[{"number":901,"_id":"564e15a74f310c8068c3f288","__v":0}],"ordered":false,"writeConcern":{"w":1}},"options":{}}] against localhost:27017 { type: 'debug',
message: 'executing command …
```
=> Fix Automattic/mongoose#3481; flush callbacks on error

lib/wireprotocol/2_4_support.js, lib/wireprotocol/2_6_support.js
Up to 8ad542a5cf3c42c58928dc13175b584a29536aaf, each `explain()` was hard-limited to finding only the first matching document. Currently, however, if the user actually *does* specify a limit using `find().limit(N).explain()`, it will be ignored and **all** documents will be found.
This commit fixes `explain()`so that it finds all documents if no limit is specified, or finds the first N documents if a `limit()` is specified.
=> fix explain() in 3.0 or lower; find all docs, or up to specified limit()

lib/topologies/mongos.js
I found this error in mongos when logout. I checked code. 'clearCredentials' is called in same way except this. So I changed it into the same way, which it is called otherplace.
=> state is not defined in mongos. 

lib/topologies/replset.js, test/tests/functional/rs_mocks/read_preferences_tests.js
If the read preference is `primaryPreferred` or `secondaryPreferred`, `isConnected()` should return true if either a primary or secondary node are connected.
JIRA ticket: [https://jira.mongodb.org/browse/NODE-628](https://jira.mongodb.org/browse/NODE-628)
=> Allow connection to secondary if primaryPreferred or secondaryPreferred

lib/connection/connection.js
Getting a lot of these errors in node 0.10:
```
Uncaught TypeError: Object #<CleartextStream> has no method 'unref'
at Connection.destroy (node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:441:21)
at null.<anonymous> (node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:114:16)
at CleartextStream.<anonymous> (node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:144:49)
```
Looks like crypto streams don't have `unref()` in node 0.10: https://github.com/nodejs/node/blob/d6859151a49e6558316dff5620d3ebc4788bc148/lib/tls.js
=> fix: only call unref if it exists

lib/topologies/server.js
This PR fixes an issue that, the driver emits an error when each retry fails and doesn't emit an error when retries reach the limit, and driver stops retry.
After this PR, each retry doesn't emit an error, and error is only emitted when retries fails after reaching retry limit.
`reconnectErrorHandler` was being used when an already established
connection errors out, however this should be used instead when a retry
errors out.
=> Fix retry mechanism throwing an error on each retry and not on retry failure.

lib/connection/pool.js
since that connection is still in the connectingConnections array, getAll() returns 1 connection and doesn't restart the pool.
However pool.isConnected() returns false since connection.isConnected() returns false and pool.state was left as CONNECTING. All new work gets deferred on the disconnectHandler waiting for reconnection which will never happen.
=> Pool gets stuck if a connection marked for immediateRelease times out

lib/connection/logger.js, test/tests/functional/pool_tests.js
```
at Logger.debug (node_modules/mongodb/node_modules/mongodb-core/lib/connection/logger.js:74:5)
at new Connection (node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:68:41)
at Pool.connect (node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:225:20)
at Server.connect (node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1010:15)
at Server.connect (node_modules/mongodb/lib/server.js:318:17)
at open (node_modules/mongodb/lib/db.js:235:19)
at Db.open (node_modules/mongodb/lib/db.js:258:44)
```
When using options.logger
=> Avoid TypeError: currentLogger is not a function

lib/topologies/replset_state.js
Allow primary to be returned when secondaryPreferred is passed and there are no secondaries. Fixes #116
=> Allow primary to be returned when secondaryPreferred is passed 

lib/topologies/mongos.js, lib/topologies/replset.js
when ops jobs are stored using `disconnectHandler.add` wrong opType was 
specified:
- in /lib/topologies/replset.js: 
'insert' was used instead 'update' and 'remove'
- in /lib/topologies/mongos.js:
’insert' was used instead of 'remove'
this lead to wrong operations being executed when connection was reestablished ( most of the time leading to operation error )
=> fix wrong opType passed to disconnectHandler.add

lib/connection/commands.js, lib/connection/connection.js
Hi Christian,
Re: https://github.com/Automattic/mongoose/issues/4457, looks like the option added in https://github.com/mongodb/js-bson/pull/116 can't be set from mongodb-core or any higher level tools. Not sure how this relates to the `promoteValues` option you added in https://github.com/christkv/mongodb-core/commit/b1a482b9a2f068687cd490f08cd0853d493c9b84 but would be great to have some way to set `promoteBuffers` from mongoose
=> Allow setting promoteBuffers

lib/cursor.js
Hi Christian,
Found an annoying issue where a cursor.next() will never fire its callback if the underlying topology ran out of `reconnectTries` or if `autoReconnect` is off. Came up when looking at https://github.com/Automattic/mongoose/issues/4581.
=> Fire callback when topology was destroyed

lib/topologies/replset.js, test/tests/functional/rs_mocks/operation_tests.js
`count` should not hangs on when replicat have only one primary but have `secondaryPreferred` preferred.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/christkv/mongodb-core/141)
=> NODE-798 Driver hangs on count command in replica set with one member

lib/connection/pool.js, test/tests/functional/cursor_tests.js
When running on mongo 2.4 and 2.6, the killCursor command does not expect a response, but the work is added to the connection.workItems list anyway.  As a result, the connection.workItems array will slowly leak memory as cursors are killed on those versions of mongo.
=> Dont leak connection.workItems elments when killCursor is called

lib/cursor.js
We are seeing a crash in mongodb-core when using a tailable cursor.
I have been unable to generate a test case that causes the problem but the exception occurs because doc is undefined so the access of .$err blows up.
=> Fix undefined exception when no doc.

lib/connection/pool.js
Re: Automattic/mongoose#4905
`tls.connect()` can throw a synchronous error, so it's best to ensure pool reports the error asynchronously so downstream callbacks don't get surprise same-tick callbacks
=> emit error asynchronously when SSL connection throws

lib/topologies/server.js
This allows to set connectionTimeout as 0 disabling the node.js idle timeout (https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback). The socket will then use the kernel default timeout (issue #161)
=> Defaults to 2000 only if connectionTimeout is not a number

lib/topologies/shared.js
The require function lookup algorithm already is relative to the file
you are requiring from.
=> remove dynamic require

index.js
This is causing the require of bson-ext to always fail and is causing issues with buffer deserialization in mongoose when bson-ext is used.
=> fix requiring bson-ext

lib/connection/connection.js
This option is needed when you have ipv4 interface and ipv4/v6 addresses at mongodb servervs, but only ipv6 connectivity to mongodb servers.
=> 'family' was added to socket options to provide high priority for ipv6 addresses

lib/connection/pool.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, lib/topologies/shared.js, lib/utils.js, test/tests/functional/mongos_mocks/mixed_seed_list_tests.js, test/tests/functional/mongos_mocks/multiple_proxies_tests.js, test/tests/functional/mongos_mocks/proxy_failover_tests.js, test/tests/functional/mongos_mocks/proxy_read_preference_tests.js, test/tests/functional/mongos_mocks/single_proxy_connection_tests.js, test/tests/functional/rs_mocks/add_remove_tests.js, test/tests/functional/rs_mocks/all_servers_close_tests.js, test/tests/functional/rs_mocks/connection_tests.js, test/tests/functional/rs_mocks/failover_tests.js, test/tests/functional/rs_mocks/maintanance_mode_tests.js, test/tests/functional/rs_mocks/monitoring_tests.js, test/tests/functional/rs_mocks/no_primary_found_tests.js, test/tests/functional/rs_mocks/operation_tests.js, test/tests/functional/rs_mocks/primary_loses_network_tests.js, test/tests/functional/rs_mocks/read_preferences_tests.js, test/tests/functional/rs_mocks/step_down_tests.js, test/tests/functional/sdam_monitoring_mocks/mongos_topology_tests.js, test/tests/functional/sdam_monitoring_mocks/replset_topology_tests.js, test/tests/functional/sdam_monitoring_mocks/single_topology_tests.js, test/tests/functional/single_mocks/timeout_tests.js
We already include a polyfill for `Object.assign` in the shared
topology utils, so this change moves that to a more centralized
location and replaces all inline implementations of a similar
`extend` method.
=> refactor(assign): move assign to shared utils, replace extend

lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js
For Server, ReplSet and Mongos, fix their `.cursor()` method documentation to correctly represent this method's arguments and return value.
This resolves [NODE-1086](https://jira.mongodb.org/browse/NODE-1086).
=> NODE-1086: fix .cursor() documentation for Server, ReplSet, and Mongos

lib/topologies/server.js
According to the SDAM specification, when a server isMaster fails either
due to a network issue, the server is not available, or ok !== 1 then
the server type must change to Unknown. This must then emit a
serverDescriptionChanged event since the type has changed.
This pull emits that event now when the server is closed to set it as
Unknown, and when the server reconnects to set it back to the proper
type. This was previously happening on single server types.
https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#type
Also I noticed a lot of tests seem to be generating `(node:46897) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: mock server is in destroyed state` and the …
=> Emit SDAM events on close and reconnect:

index.js
Previously `MongoError` and `MongoNetworkError` were contained inside `MongoError`. This PR moves them to be top-level exports of mongodb-core.
=> NODE-1080: export MongoError and MongoNetworkError at top-level

lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/replset_state.js, lib/topologies/server.js, test/tests/unit/sessions_tests.js
This adds required tracking of `logicalSessionTimeoutMinutes` from ismaster responses according to the new sections in the SDAM spec:
- https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#logical-session-timeout
- https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#logicalsessiontimeoutminutes
=> feat(sessions): track `logicalSessionTimeoutMinutes` for sessions

lib/cursor.js, lib/topologies/server.js, test/tests/functional/cursor_tests.js
@adriaanmeuris and @bendytree 's repro for Automattic/mongoose#4513 helped uncover a few couple nasty edge cases with how mongodb-core handles `autoReconnect: false`.
First up, with the server topology, the below script will hang forever, because the `count()` call will wait forever for a reconnect.
```javascript
const mongodb = require('mongodb');
run().catch(error => console.error('Uncaught error', error.stack));
async function run() {
const db = await mongodb.MongoClient.connect('mongodb://localhost:27017/test', {
socketTimeoutMS: 500,
poolSize: 1,
autoReconnect: false
});
db.on('timeout', function() {
console.log('Got timeout');
});
db.on('disconnected', function() {
console.log('Disconnected');
});
await db.dropDatabase();
await db.collection('Test').insertOne({});
try {
await …
```
=> Improve handling for autoReconnect: false with timeouts

lib/auth/scram.js
Remove `_hiCache` from `lib/auth/scram.js`.
`_hiCache` was never pruned, and in some environments grew without bound. This leaked memory, used more time to garbage collect, and increased call latencies. Testing showed that removing the cache had no adverse impact compared to mongodb-2.1.18, an older version of the mongo driver without _hiCache.
=> re issue-220: remove _hiCache, not needed and fixes memory leak

index.js, lib/connection/pool.js, lib/cursor.js, lib/sessions.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, lib/utils.js, lib/wireprotocol/2_6_support.js, lib/wireprotocol/3_2_support.js, test/tests/unit/sessions_tests.js, test/tests/unit/single/sessions_tests.js
This is the first step in full support for driver sessions, implementing the `ClientSession` and `ServerSession` types, as well as the `ServerSessionPool`.  The rest of the behavior defined in the spec relates specifically to the porcelain layer ("Where does the pool live?", "Does the topology we're connecting to support sessions?", etc). 
Required reading: https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst
**NOTE:** This branch is based on the `cluster-time-gossiping` branch, so it might look a little big at first. Once #219 is merged this should reduce in size dramatically.
=> feat(driver-sessions): Implement driver sessions for the core driver

lib/auth/scram.js
restores the`_hiCache` functionality, but without the unbounded cache growth
=> cache the ScramSHA1 salted passwords, capping the cache at 200 entries

lib/connection/utils.js
Getting the following error when running mongoose against the 3.0 driver branch:
```javascript
> mongoose@5.0.0-pre test /home/val/Workspace/MongoDB/mongoose
> mocha test/*.test.js test/**/*.test.js
/home/val/Workspace/MongoDB/mongoose/node_modules/require_optional/index.js:56
throw new Error(f('no optional dependency [%s] defined in peerOptionalDependencies in any package.json', parts[0]));
^
Error: no optional dependency [snappy] defined in peerOptionalDependencies in any package.json
at find_package_json_with_name (/home/val/Workspace/MongoDB/mongoose/node_modules/require_optional/index.js:56:11)
at require_optional (/home/val/Workspace/MongoDB/mongoose/node_modules/require_optional/index.js:69:13)
at Object.retrieveSnappy (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb-core/ …
```
=> fix(utils): don't throw if no snappy

lib/topologies/replset.js
When a replica set topology has an invalid name, core emits an error
stating that no primary or secondary found in the replica set, which can
cause some user confusion. This simply expands the language to include
that the name may be invalid to help with debugging.
=> More verbose replica set errors emission:

lib/connection/connection.js, test/tests/functional/pool_tests.js
Adding the fix from #234 to 3.0.0 branch.
=> fix(connection): fixing leak in 3.0.0

lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, test/tests/unit/mongos/sessions_tests.js, test/tests/unit/replset/sessions_tests.js, test/tests/unit/single/sessions_tests.js
The ReplSet and Mongos topologies are really just containers for a
number of Server topologies.  Hence, when initially implementing
cluster time gossipping a `clusterTimeWatcher` was used to
coordinate reported times from child topologies. Unfortunately,
this ignored the need to _read_ the deployment (parent) cluster
time.  Instead Server topologies internal to the container
topologies now have a concept of a `parent`, which also simplifies
the code dramatically.
NODE-1088
**NOTE:** this also contains an additional fix for temporarily skipping the 1:1 topology guarantee of the driver sessions spec, please disregard during review
=> refactor(cluster-time): topologies should report consistent times

lib/connection/pool.js, lib/sessions.js, test/mock/index.js, test/tests/unit/common.js, test/tests/unit/single/sessions_tests.js
Version 3.6 of the server introduces support for [causal consistency of reads](https://github.com/mongodb/specifications/blob/master/source/causal-consistency/causal-consistency.rst), this pull request adds support for this feature to the core layer of the driver.
=> feat(causal-consistency): add support for causally consistent reads

lib/topologies/replset.js
Port of #231 to 3.0.0.
When a replica set topology has an invalid name, core emits an error
stating that no primary or secondary found in the replica set, which can
cause some user confusion. This simply expands the language to include
that the name may be invalid to help with debugging.
=> feat(replset): more verbose replica set errors emission 

lib/cursor.js
I made a mistake in https://github.com/mongodb-js/mongodb-core/pull/215 that is likely causing Automattic/mongoose#5794: `reconnect` isn't a topology option for replica sets or mongos, so my change could cause cursors to incorrectly think that the topology will never reconnect. I suspect this issue will be fixed if we just limit the "fail fast if `autoReconnect` disabled and topology is disconnected" to just single servers.
=> fix(cursor): check for autoReconnect option only for single server

test/tests/functional/pool_tests.js
This removes a `.only` in the pool tests (causing it to run just one test) that got left in changes via in #235 🍍
=> test(pool): remove .only in test

lib/sessions.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, lib/topologies/shared.js, test/tests/unit/single/sessions_tests.js
* This allows us to generically end a number of sessions with a
single command, mixed into all three supported topologies.
* We also support a `skipCommand` option on the session's
`endSession` so that we can clear the data stored in these.
* Finally, ClientSession is now an EventEmitter, so we can track
them in a collection on the top level MongoClient and clean
up when appropriate.
=> refactor(endSessions): add helper for endSessions on topologies

lib/connection/connection.js
Upon closer inspection, #183 was actually very much backwards breaking and should not have been merged. This issue causes https://github.com/Automattic/mongoose/issues/5760 via https://github.com/Automattic/mongoose/commit/93e771ce5678c20da3a8dd08a4b77de8a1380446 .
The problem with #183 is that [`net.createConnection()`](https://nodejs.org/api/net.html) calls [`dns.lookup()`](https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback) with the `family` option always set. If the `family` option is not set, `dns.lookup()` will return both ipv4 and ipv6 addresses, but since mongodb-core always sets `family` now, the driver can only connect to ipv4 or ipv6 depending on the value of `family`. In particular, this means that any user that was connecting to an ipv6 address now …
=> fix(connection): default `family` to undefined rather than 4

lib/auth/plain.js
This fixes a problem that arises when using Rollup to bundle an application that uses this library.
```
[!] Error: Identifier 'BSON' has already been declared
node_modules/mongodb-core/lib/auth/plain.js (11:4)
9:   , MongoError = require('../error');
10:
11: var BSON = retrieveBSON();
^
12:
13: var AuthSession = function(db, username, password) {
```
=> Don't redeclare BSON variable

.travis.yml, lib/connection/pool.js, lib/sessions.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/shared.js, lib/wireprotocol/3_2_support.js, test/tests/unit/common.js, test/tests/unit/mongos/retryable_writes_tests.js, test/tests/unit/replset/retryable_writes_tests.js
ticket: https://jira.mongodb.org/browse/NODE-1105
spec: https://github.com/mongodb/specifications/blob/master/source/retryable-writes/retryable-writes.rst
This implements the basic building blocks for support for retryable writes in the core driver.  The code sections are implementations of the pseudocode documented in the spec linked above.  The feature is "enabled" on supported servers by passing a `retryWrites: true` option down to the topology's supported write operations (insert/update/remove), as well as a valid session.  All other details should be covered by the spec.
It should be mentioned that this includes a preliminary bug fix for the pool supporting a "minimum pool size".  This was a problem encountered during testing because the simulation of a lost connection resulted in a …
=> feat(retryable-writes): add basic support for retryable writes to mongodb-core

lib/topologies/server.js
This fixes the misspelling of `initialConnect` in `lib/topologies/server.js`.
Closes #249
=> style(server): fix variable typo

lib/topologies/read_preference.js
This updates the ReadPreference in the core module to serve as a
full replacement for the one in the porcelain layer.
NODE-1187
=> refactor(read-preference): merge missing api from native version

lib/connection/connection.js
Hi, this is second part of PRs. The first is #243.
This will allow to `mongo-native-driver` to send `ciphers` and `ecdhCurve` options to `mongodb-core`
One moment I'm not sure:
[here](https://github.com/mongodb-js/mongodb-core/blob/2.0/lib/connection/connection.js#L431), then I've tested with mongos and servers these two options already was in `sslOptions` object, so I leave this place.
Related with #245
=> fix(connection): accept incoming missed ssl options from mongo-native-driver

lib/topologies/replset_state.js, test/mock/lib/server.js, test/tests/unit/replset/sessions_tests.js
Arbiters in a ReplSet should not be taken into consideration if
they report a `logicalSessionTimeoutMinutes`.
NODE-1188
=> fix(sessions): ensure that we ignore session details from arbiters

lib/topologies/mongos.js, test/tests/unit/mongos/events_tests.js
Not all of the listeners were being removed when a server was closed, causing a memory leak on reconnect. 
This removes the `serverDescriptionChanged` listener when a server has been closed.
NODE-1216
=> Remove listener when mongos destroyed

lib/connection/pool.js, lib/topologies/server.js, lib/utils.js, test/tests/functional/mongos_mocks/mixed_seed_list_tests.js, test/tests/functional/mongos_mocks/multiple_proxies_tests.js, test/tests/functional/mongos_mocks/proxy_failover_tests.js, test/tests/functional/mongos_mocks/proxy_read_preference_tests.js, test/tests/functional/mongos_mocks/single_proxy_connection_tests.js, test/tests/functional/rs_mocks/add_remove_tests.js, test/tests/functional/rs_mocks/all_servers_close_tests.js, test/tests/functional/rs_mocks/connection_tests.js, test/tests/functional/rs_mocks/failover_tests.js, test/tests/functional/rs_mocks/maintanance_mode_tests.js, test/tests/functional/rs_mocks/monitoring_tests.js, test/tests/functional/rs_mocks/no_primary_found_tests.js, test/tests/functional/rs_mocks/operation_tests.js, test/tests/functional/rs_mocks/primary_loses_network_tests.js, test/tests/functional/rs_mocks/read_preferences_tests.js, test/tests/functional/sdam_monitoring_mocks/mongos_topology_tests.js, test/tests/functional/sdam_monitoring_mocks/replset_topology_tests.js, test/tests/functional/sdam_monitoring_mocks/single_topology_tests.js, test/tests/functional/single_mocks/compression_tests.js, test/tests/functional/single_mocks/timeout_tests.js, test/tests/unit/common.js, test/tests/unit/mongos/sessions_tests.js, test/tests/unit/single/sessions_tests.js
=> chore(assign): replace assign with native Object.assign

lib/topologies/replset.js, test/tests/unit/replset/read_preference_tests.js
Ensures that when readPreference is `secondary`, the `connect`
event is not triggered until connection has been established
with a secondary.
Fixes NODE-1089
=> fix(secondaries): fixes connection with secondary readPreference

test/environments.js
The sharded environment was previous broken due to the fact that the environment setup was not properly waiting for async events to occur in order (setup of mongod/mongos instances). This fixes all that.
=> NODE-1075 reenable sharded environment for testing (core) 

lib/connection/connection.js, test/tests/functional/connection_tests.js
If the user does not specify an IP family, we will attempt to
connect first via IPv6, and fall back to IPv4 if that fails
Currently WIP as I need to write unit tests for this.
=> feat(connection): attempt both ipv6 and ipv4 when no family entered

lib/topologies/server.js, test/tests/functional/server_tests.js
This updates the error message received when a user attempts to connect to a server running an older version of MongoDB than the latest Node.js Driver version supports. For instance, using the 3.x version of the driver to connect to a server running something below MongoDB 2.6. 
@daprahamian and I paired on this PR 💯 
@mbroadst do you think we should break up the error messages into other files to do more explicit testing?
NODE-1186
=> fix(sdam): more explicit wire protocol error message

.evg.yml
We change where `nvm` is installed to keep our testing environment from messing up anything else. 🍐 'd with @mbroadst on this and about to merge it ⚡️
=> Updates to Evergreen Config

lib/uri_parser.js, test/tests/spec/connection-string/invalid-uris.json, test/tests/spec/connection-string/invalid-uris.yml
This updates the connection string tests to the latest version from the specifications and fixes the `uri-parser` to catch malformed URIs early.
🍐 'd on this with @mbroadst. Ideally at some future point we'll have a grammar for the connection string, but in the meantime we'll use Node's `url` module to check for malformations. 
_PS sorry about the commit username, I will go and fix that right now haha._ 
Fixes NODE-1282
Related to https://github.com/mongodb/node-mongodb-native/pull/1656
=> Re-sync Connection String Tests

lib/topologies/replset.js
Make sure to not remove the primary on an error until after the retry
=> fix(retryableWrites): only remove primary after retry

lib/connection/pool.js, test/tests/functional/server_tests.js
This is a somewhat strange case. The below script will print an error immediately but continue retrying connecting in the background forever:
```javascript
const mongodb = require('mongodb');
mongodb.MongoClient.connect('mongodb://thisdoesntexist:27017', { reconnectTries: 0 }).
then(() => console.log('success'), err => console.log('error', err));
```
If you set `reconnectTries` to 1, the script prints an error and then exits.
```javascript
const mongodb = require('mongodb');
mongodb.MongoClient.connect('mongodb://thisdoesntexist:27017', { reconnectTries: 1 }).
then(() => console.log('success'), err => console.log('error', err));
```
This patch fixes that particular issue. But this issue surfaced as part of investigating Automattic/mongoose#6028, which brings up a valid concern: why does …
=> fix(connection): make pool not try to reconnect forever when reconnectTries = 0

lib/sessions.js, lib/topologies/shared.js
Currently, endSessions filters out any calls that happen while
the topology is connected. However, it is impossible to send
an endSessions command if you are not connected. This fix allows
sessions to be ended while the topology is connected.
Also adds a helper method that `native` can call to easily end all pooled sessions.
WIP b/c this currently breaks APM tests in native.
=> Help 5834:  fix(sessions): actually allow ending of sessions

lib/topologies/replset.js, test/tests/unit/replset/auth_stalling_tests.js
ReplicaSet was storing the authentication call in the disconnectHandler
when it didn't need to, leading to auth stalling. From now on, will
only store handlers if ReplSet is not actually connected.
@durran Can you link against this and verify that it fixes your issue?
=> fix(auth): prevent stalling on authentication when connected

lib/connection/pool.js
We were only passing the error, and not the auth result,
to the auth callback in the pool
=> fix(auth): pass auth result to callback

lib/sessions.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/shared.js, lib/wireprotocol/3_2_support.js, lib/wireprotocol/shared.js
These are the changes required for the core driver in order to support transactions in the mongodb node driver. The meat of the changes exist in the `ClientSession` object, as well as a smattering of logical changes related to whether a given session is currently in a transaction. Please try to focus on functional criticisms, I guarantee you if you're having thoughts about overall architecture I have probably had nightmares about them in the past few weeks
=> feat(transactions): add initial support for multi-stage transactions on replicasets

lib/sessions.js
Sessions are meant to be cached, and the `endSessions` command is
only meant to be used as a way to signal to the server that cached
sessions will no longer be used (due to the client closing). We
were sending too many `endSessions` commands, now we just send the
one.
NODE-1418
=> fix(sessions): never send `endSessions` from a `ClientSession`

lib/topologies/mongos.js, lib/topologies/replset.js, lib/wireprotocol/3_2_support.js, test/tests/unit/replset/transactions_feature_decoration_tests.js
We started sending txnNumber for non-transaction non-retryable
commands, which causes errors against transaction-enabled servers
Fixes NODE-1466
=> fix(transactions): do not send txnNumber for non-write commands

lib/topologies/replset.js
This was accidentally introduced during the following refactor:
https://github.com/mongodb-js/mongodb-core/commit/cd44d70f57661ad63c6a65558ffcfa38d1e7d3a2#diff-dc27eebcc66ed957fe1f8d58c5387d0dL856
There isn't any negative side effects, just unnecessary function calls being made.
Obsoletes #310.
=> Removing double timeout clear

package.json
This pr fixes an issue where bson-ext uses an outdated version and as a result the current mongodb [documents](http://mongodb.github.io/node-mongodb-native/3.0/installation-guide/installation-guide/) are incorrect, running `npm install bson-ext --save` will install a package that won't be detected by the driver since it's outside the expected version number, ideally until this is merged the driver documentation should be updated as well, this has a heavy impact on node.js servers as they will be running the JS version of Bson possibly in production without knowing it.
=> updated package.json peerOptionalDependencies to support bson-ext 2.0.0+

.evergreen/config.yml
Fixes NODE-1495
Is there a reason we are only using a 2d matrix? [It seems like C-Sharp uses a 5d one](https://github.com/mongodb/mongo-csharp-driver/blob/master/evergreen/evergreen.yml#L440).
=> chore(evergreen): add 4.0 to evergreen matrix

lib/wireprotocol/2_6_support.js, lib/wireprotocol/3_2_support.js, package.json, test/tests/unit/wire_protocol_test.js
The bypassDocumentValidation key will only be set if it explicitly
receives a true, otherwise it remains undefined.
Fixes NODE-1492
=> fix(wireprotocol): only send bypassDocumentValidation if true

index.js, lib/connection/pool.js, lib/error.js, test/tests/unit/pool_tests.js
Presently we wrap all reported `writeConcernError`s with a simple
`MongoError`, which makes it difficult to specialize on this case
in situations such as retry logic.
NODE-1516
=> feat(error): add more specific error type for write concern errors

lib/uri_parser.js, test/tests/unit/connection_string_spec_tests.js
Arrays passed in to the uri string by repeating fields
are now parsed correctly.
Fixes NODE-1605
=> fix(uri-parser): Incorrect parsing of arrays

lib/cursor.js
This PR fixes a typo in the `_find()` function when validating the results cursor.
A type check is lacking the `typeof` operator (line 241).
It is written correctly a few lines below (line 252).
/cc @christkv (author of this code)
=> fix(cursor): typo in _find() cursor validation

lib/sdam/monitoring.js, lib/sdam/server.js, lib/sdam/server_selectors.js, lib/sdam/topology.js
NOTE: this builds on the previous PR so it will look a little huge until that is rebased.
Most notably here we introduce the ability to monitor servers, in order to keep the topology state machine up-to-date. A cool feature introduced, once monitoring was possible, is that we no longer have to explicitly call `connect` on a topology object.
This works:
```
it('should work without explicitly calling connect', function(done) {
const config = this.configuration;
const client = new Topology({ host: config.host, port: config.port });
const ns = `${this.configuration.db}.insert_test`;
client.insert(ns, { a: 1 }, function(err, result) {
expect(err).to.not.exist;
expect(result).to.exist;
done();
});
});
```
=> NODE-1259(continued): add support for monitoring, and improve server selection

lib/uri_parser.js
Enable parsing of comma-separated option values into arrays.
Fixes NODE-1612
=> fix(uri-parser): Parse comma-separated option values

lib/cursor.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, test/tests/functional/mongos_server_selection_tests.js
This makes it much easier to drop-in replace the upcoming unified
`Topology` type by making the internal APIs the same.
NODE-1625
=> refactor(topologies): rename `getServer` to `selectServer`

lib/topologies/mongos.js, lib/topologies/server.js, test/tests/unit/mongos/reconnect_tests.js
Our mongos reconnect logic involved creating a new Server+Pool
per proxy per iteration of the reconnect logic. These instances
were never cleaned up, resulting in a huge number of connections
when the proxies finally reconnected.
Fixes NODE-1403
~WIP b/c I am trying to figure out how to test this.~ I have a test now. It takes a long time though :(
=> fix(mongos): fix connection leak when mongos reconnects

lib/auth/scram.js, lib/connection/commands.js, lib/connection/connection.js, lib/connection/pool.js, lib/topologies/replset_state.js, lib/topologies/shared.js, package-lock.json, package.json, test/tests/functional/server_tests.js, test/tests/unit/common.js, test/tests/unit/scram_iterations_tests.js
Hi,
The fix of [NODE-1461](https://jira.mongodb.org/projects/NODE/issues/NODE-1461?filter=allissues) ( commit 7c71e199190a53017b921e88200cdba3889ca23c) break compatibility with node.js < 4.5 and node.js < 5.9 and  and start to affect downstream packages like Automattic/mongoose#6884
This pull request uses `safe-buffer` to polyfill and [it is suggested by official node.js](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/)
The polyfill won't change any existing behavior and will call native method directly if it is supported.
=> fix(buffer): use safe-buffer polyfill to maintain compatibility

lib/connection/apm.js, test/tests/unit/apm_tests.js
Properly upconverts query-wrapped commands in OP_QUERY to the
proper apm format
Fixes NODE-1655
=> fix(apm): fix upconversion for OP_QUERY in apm

test/config.js, test/tests/functional/basic_single_server_auth_tests.js, test/tests/functional/client_metadata_tests.js, test/tests/functional/cursor_tests.js, test/tests/functional/error_tests.js, test/tests/functional/extend_cursor_tests.js, test/tests/functional/max_staleness_tests.js, test/tests/functional/operation_example_tests.js, test/tests/functional/operations_tests.js, test/tests/functional/replset_server_selection_tests.js, test/tests/functional/sdam_monitoring_mocks/single_topology_tests.js, test/tests/functional/server_tests.js, test/tests/functional/shared.js, test/tests/functional/single_mocks/compression_tests.js, test/tests/functional/single_mocks/timeout_tests.js, test/tests/functional/tailable_cursor_tests.js, test/tests/functional/undefined_tests.js
There are a number of tests that are meant to be run against
replicasets which were using a `Server` topology. The errors were
not immediately obvious, until my primary changed from the default
port of 31000 and many `Not Master` errors started popping up.
NODE-1687
=>  test(*): use `newTopology` instead of explicitly creating Servers

lib/uri_parser.js, test/tests/unit/connection_string_tests.js
re: Automattic/mongoose/issues/7167 ( replicaSet details and native code sample there ).
If a setName starts with a number, the new url parser will coerce the replicaSet value passed into the connection string to a number e.g. `replicaSet=456abc` becomes `456`.  Setting the value in the connection options works as expected. This change adds replicaset to the set of known strings.
=> fix(uri_parser) bypass number coercion for replicaSet val in connection string

lib/sdam/monitoring.js, lib/sdam/topology.js, lib/sdam/topology_description.js, test/config.js, test/environments.js, test/tests/functional/cursor_tests.js, test/tests/functional/replset_server_selection_tests.js, test/tests/functional/server_tests.js, test/tests/functional/single_mocks/compression_tests.js, test/tests/functional/single_mocks/timeout_tests.js, test/tests/unit/sdam_spec_tests.js
This is a PR resulting from lessons learned when fixing memory leaks in the old `mongos` topology implementation. Along the way, I discovered we never actually ran the test suite in core against the new SDAM implementation, so that has been added as well here.
=> NODE-1683: defensively avoid memory leaks in new SDAM layer

lib/topologies/mongos.js, lib/topologies/replset.js, test/tests/unit/replset/compression_tests.js
This allows for options determined during uri parsing to make it
down to the creation of child Server instances using the legacy
SDAM topology classes.
NODE-1798
=> fix(mongos-replset): pass connect options to child server instances

lib/connection/commands.js, lib/cursor.js, lib/wireprotocol/2_6_support.js, lib/wireprotocol/3_2_support.js, lib/wireprotocol/shared.js
This is a mostly cosmetic change to make the two wire protocol classes easier to reason about:
- refactor to use a common `raw` property on the cursor state
- utilizing a common function for determining common query options
- converting the wire protocols to classes to make them easier to read and determine common code
=> refactor(wire-protocol): modernize and clean wire protocol

lib/cursor.js, lib/topologies/server.js, lib/wireprotocol/2_6_support.js, lib/wireprotocol/3_2_support.js, lib/wireprotocol/shared.js
This completes the work to make a semi-consistent api across all methods on `WireProtocol`, opening up the door for even further consolidation of the codebase here (perhaps `WireProtocolBase`, and switching between `OP_QUERY` and `OP_MSG`)
=> refactor(wire-protocol): `command` and `query` now take callbacks

lib/cursor.js, lib/sdam/server.js, lib/topologies/server.js, lib/wireprotocol/2_6_support.js, lib/wireprotocol/3_2_support.js, lib/wireprotocol/shared.js, test/tests/functional/server_tests.js, test/tests/unit/wire_protocol_test.js
All wire protocol method now just take a (selecte) server, rather
than a `pool`, `bson` and `topology` instances - these are all
housed IN a server anyway.
NODE-1799
=> refactor(wire-protocol): simplify and make consistent signatures

package.json
Running `npm run format` on Windows only formats `index.js` because the other two paths start with single quotes which is considered an invalid path. Remove single quotes to work on both Windows & Linux
=> fix(prettier): fix prettier file paths for Windows

lib/connection/apm.js, lib/connection/commands.js, lib/wireprotocol/2_6_support.js, lib/wireprotocol/3_2_support.js, lib/wireprotocol/shared.js, test/tests/functional/mongos_mocks/proxy_read_preference_tests.js, test/tests/unit/apm_tests.js
Most of the 2.6 and 3.6 wire protocol implementations are using
commands, but they don't internally reuse the available `command`
method. This does that as much as possible, reducing a large
amount of duplicate code, and improving readability.
- converted `killCursors` to reuse `command` (3.2 only)
- simplify `command` options handling
- converted `getMore` to use `command (3.2 only)
- fix mongos sharded tests to pass read preference in as option
not in the command
- converted write commands to use `command` internally (2.6+3.2)
` converted `query` to reuse `command` (3.2 only)
- remove needless copy of options in `Query` class (fixed apm too)
- refactor `databaseNamespace` and `collectionNamespace` (2.6+3.2)
=> refactor(wire-protocol): reuse `command` where possible

lib/auth/gssapi.js, lib/auth/mongocr.js, lib/auth/plain.js, lib/auth/scram.js, lib/auth/sspi.js, lib/auth/x509.js, lib/connection/pool.js, lib/sdam/server.js, lib/topologies/server.js
This is the final work required for OP_MSG support. All instantiations of `Query` have been reduced to two points in the code: the `WireProtocol` class(es), and what I'm renaming a `commandWriter` in the `Pool`. It should now be exceeding easy to switch out the `OP_QUERY` implementation for `OP_MSG` without having to impact very much of the codebase.
=> NODE-1830: reduce query instantiation

lib/connection/pool.js, lib/wireprotocol/shared.js
For legacy reasons, `Pool.write` takes an array of commands even
though the driver doesn't actually do anything with an array. It's
easier for the future to accurately reflect what we are passing
around.
NODE-1844
=> refactor(wire-protocol): only single commands are written to pool

lib/error.js, lib/sessions.js, lib/utils.js
This is the core component (the meat) of NODE-1741. There were some design decisions made here, most notably that only a `Promise` may be returned from the lambda passed into `withTransaction`. Outside of that, this mostly follows the spec to the letter.
=> NODE-1741: implement convenient transactions api (core)

index.js, lib/auth/auth_provider.js, lib/auth/gssapi.js, lib/auth/mongo_credentials.js, lib/auth/mongocr.js, lib/auth/plain.js, lib/auth/scram.js, lib/auth/sspi.js, lib/auth/x509.js, lib/connection/pool.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, test/tests/functional/basic_replset_server_auth_tests.js, test/tests/functional/basic_single_server_auth_tests.js, test/tests/functional/cursor_tests.js, test/tests/functional/pool_tests.js, test/tests/functional/server_tests.js, test/tests/functional/shared.js, test/tests/unit/mongos/reconnect_tests.js, test/tests/unit/replset/auth_tests.js, test/tests/unit/scram_iterations_tests.js
A major refactor to rewrite core to use MongoCredentials objects
instead of individually passing around auth fields. Also removes
significant amounts of duplicate code in auth providers. Also
switches to the async version of crypto.randomBytes to
resolve #307.
Fixes NODE-1436
Fixes NODE-1442
=> refactor(auth): switch to MongoCredentials and cleanup

.travis.yml, lib/connection/pool.js
Sessions information is not presently applied to OP_MSG messages
because of a patch that was left out of the OP_MSG PR. The real
fix for this is to merge all of the sessions-related code in
our pool into the `command` wire protocol method, but that work
shouldn't hold up sessions support today.
=> fix(sessions): enable sessions in OP_MSG

lib/connection/connect.js, lib/connection/connection.js, lib/connection/pool.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, test/tests/functional/connection_tests.js, test/tests/functional/pool_tests.js, test/tests/functional/server_tests.js
Primary goals for this work (from jira ticket):
- Decouple Connection from the Pool by not passing in a messageHandler to the constructor, but use a message event instead
- Move the "connect" logic for creating and initially connection connections out of Connection into its own method, a la net.connect
=> NODE-1845: allow connection to be shared with mock server

lib/connection/connect.js, lib/connection/connection.js, lib/connection/pool.js, lib/topologies/server.js
This removes the initial handshake code from the middle of the
Server topology implementation into our new `connect` method,
taking us one step closer to isolating all connection
initialization to a single location. The next step will be to
authenticate the connections.
NODE-1863
=> refactor(handshake): pull out initial handshake into `connect`

lib/auth/auth_provider.js, lib/auth/gssapi.js, lib/auth/mongocr.js, lib/auth/scram.js, lib/auth/sspi.js, lib/connection/connect.js, lib/connection/pool.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, test/tests/functional/pool_tests.js, test/tests/unit/replset/auth_tests.js, test/tests/unit/scram_iterations_tests.js
**NOTE:** this PR is a little big until the previous one is reviewed and merged
This moves all authentication in the entire driver into the `connect` method, greatly simplifying our view of auth in the module. Top-level methods still exist on all of the topologies, but they are no-ops that immediately call back with no error.
=> NODE-1435: move all auth to `connect`

lib/connection/pool.js, lib/cursor.js, lib/sdam/topology.js, lib/sessions.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, lib/transactions.js, lib/wireprotocol/command.js
Changes to ensure that all commands in a sharded transaction run against a single `mongos`.
Items to still do:
+ [ ] Ensure that pins are released at the appropriate times
+ [ ] Add support for new SDAM layer
=> Pin Servers during Sharded Transactions

lib/connection/pool.js, lib/sessions.js, lib/transactions.js, lib/wireprotocol/command.js
=> refactor(pool): remove all sessions-related methods out of pool

lib/connection/pool.js, lib/error.js, test/tests/unit/write_concern_error_tests.js
Makes WriteConcernErrors returned by user commands (ex: createUser)
have the same format as other WriteConcernErrors (ex: ok = 1)
Fixes NODE-1792
=> chore(WriteConcernError): update writeConcernError for user commands

lib/connection/connection.js, lib/connection/pool.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/replset_state.js, lib/topologies/server.js
This is the "core" component of NODE-1828, allowing support for a callback passed to a topology (and subsequently pool and connection) so that we can synchronize resources on client close.
=> NODE-1828: support passing callbacks to topology destroyed methods

lib/uri_parser.js, test/tests/unit/connection_string_tests.js
In #410, I removed the special case for `compression` but I intended to leave it in after Matt had some questions around whether it would break compression in native. This PR is to restore the original `compression` special case code and accompanying test.
=> fix(uri_parser): restore original compression parsing

lib/auth/scram.js
Fixes an error when connecting to MongoDB Atlas with the option `promoteBuffers: true`. Emabling that option causes the binary payload to be returned as a Node.js Buffer instance.
=> fix authentication with promoteBuffers: true

lib/connection/connect.js
Connect error handler was attempting to read properties off
of an error that had a chance of being null. Removed that,
and replaced the error generation to be more explicit.
Fixes NODE-1960
=> fix(connect): fixed syntax issue in connect error handler

lib/uri_parser.js, test/tests/unit/connection_string_tests.js
Fixes NODE-1983
Needs to be ported to `next`
=> fix(uri-parser): always treat appname as a string

lib/topologies/server.js
Admittedly this is a minor detail, but when connecting to a standalone server that is currently down using the below script:
```javascript
const mongodb = require('mongodb');
const connectionString = `mongodb://localhost:27017/test`;
run().then(() => console.log('done')).catch(error => console.error(error.stack));
async function run() {
await mongodb.MongoClient.connect(connectionString, { useNewUrlParser: true, connectTimeoutMS: 5000 });
}
```
You get the below error message:
```
Error: connect ECONNREFUSED 127.0.0.1:27017
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```
This error gets bubbled up because for some reason the pool hasn't transitioned its state from 'CONNECTING' to …
=> fix(server): emit "first connect" error if initial connect fails due to ECONNREFUSED

lib/connection/pool.js, test/tests/unit/pool_tests.js
A temporary fix that will ensure that if a connection is mid-handshake when the pool is closed, it will be destroyed as soon as the handshake call settles.
Fixes NODE-1971
needs to be ported to `node-mongodb-native#next`
=> fix(pool): clean up connections if pool is destroyed mid-handshake

lib/cursor.js
=> fix(cursor): do not truncate an existing Long

lib/connection/connect.js
I did some digging to figure out why angular universal doesn't seem to work when connecting to Atlas (https://github.com/Automattic/mongoose/issues/7838) and found an interesting quirk that may or may not be a bug.
The reason why angular universal fails is that, because of how Zone.js monkey-patches event emitters to be cancellable, `connectHandler()` cancels itself by calling `removeAllListeners('connect')` because it removes all listeners from all error events. I'm not sure why 'connect' is listed as an error event. Removing it seems to not break anything and at least enable Mongoose to connect to Atlas in angular universal.
I realize this is a risky change and might be worth waiting until a minor or major release, but I don't see how this could break anything. I might be missing …
=> fix(connect): don't treat 'connect' event as an error

lib/topologies/replset.js
We were calculating lastUpdateTime using nanoseconds instead of
milliseconds, despite calculating maxStaleness with a millisecond
lastWriteDate
=> fix(replset): correct legacy max staleness calculation
